########################################################
#
# Makefile for preparing leidenbase R package.
#
# This makefile is based nearly literally on the R
# igraph Makefile. We acknowledge our use of Gabor
# Csardi's Makefile and our gratitude for his making
# the igraph distributions and source code publicly and
# freely available.
#
########################################################

all: leidenbase

########################################################

# Main package

top_srcdir=cigraph
VERSION_LEIDENBASE=0.1.3
VERSION_IGRAPH=0.8.5

# We put the version number in a file, so that we can detect
# if it changes

version_number: force
	@echo '$(VERSION_LEIDENBASE)' | cmp -s - $@ || echo '$(VERSION_LEIDENBASE)' > $@

# Source files from the C igraph library, we don't need BLAS/LAPACK
# because they are included in R and ARPACK, because 
# we use the Fortran files for that. We don't need F2C, either.

CSRC := $(shell cd $(top_srcdir) ; git ls-files --full-name src | \
        grep -v "^src/lapack/" | grep -v "^src/f2c" | grep -v Makefile.am)
#$(info CSRC is $(CSRC))

CSRC2 := $(patsubst src/%, src/cigraph/src/%, $(CSRC))
#$(info CSRC2 is $(CSRC2))

$(CSRC2): src/cigraph/src/%: $(top_srcdir)/src/% src/cigraph/include/igraph.h
	mkdir -p $(@D) && cp $< $@

CXXSRC := $(shell git ls-files --full-name src | grep -E ".cpp$$")

# Include files from the C library

CINC := $(shell cd $(top_srcdir) ; git ls-files --full-name include)
#$(info CINC is $(CINC))
CINC2 := $(patsubst include/%, src/cigraph/include/%, $(CINC))
#$(info CINC2 is $(CINC2))

#$(info copy headers next)
$(CINC2): src/cigraph/include/%: $(top_srcdir)/include/%
	mkdir -p $(@D) && cp $< $@

# Files generated by flex/bison
#$(info parse flex/bison next)

PARSER := $(shell cd $(top_srcdir) ; git ls-files --full-name src | \
	    grep -E '\.(l|y)$$')
PARSER1 := $(patsubst src/%, src/cigraph/src/%, $(PARSER))
PARSER2 := $(patsubst src/cigraph/src/%.l, src/cigraph/src/%.c, $(PARSER1))
PARSER3 := $(patsubst src/cigraph/src/%.y, src/cigraph/src/%.c, $(PARSER2))

#$(info PARSER3 $(PARSER3))

YACC=bison -d
LEX=flex

%.c: %.y
	$(YACC) $<
	mv -f y.tab.c $@
	mv -f y.tab.h $(@:.c=.h)

%.c: %.l
	$(LEX) $<
	mv -f lex.yy.c $@

# C files generated by C configure
#$(info make cgen next)

CGEN = src/cigraph/include/igraph_threading.h src/cigraph/include/igraph_version.h

src/cigraph/include/igraph.h: templates/igraph.h.tpl
	cp templates/igraph.h.tpl src/cigraph/include/igraph.h

src/cigraph/include/igraph_threading.h: $(top_srcdir)/include/igraph_threading.h.in
	mkdir -p src/cigraph/include
	sed 's/@HAVE_TLS@/0/g' $< >$@

src/cigraph/include/igraph_version.h: $(top_srcdir)/include/igraph_version.h.in
	mkdir -p src/cigraph/include
	sed 's/@PACKAGE_VERSION@/'$(VERSION_IGRAPH)'/g' $< >$@

# R source and doc files
#$(info make r source next)

RSRC := $(shell git ls-files R man inst configure.win)

# ARPACK Fortran sources
#$(info make arpack next)

# Source files from R igraph $top_dir/tools/arpack.
ARPACK := $(shell git ls-files src/arpack | \
          grep -E '\.f$$')

# R files that are generated/copied
#$(info make r files next)

RGEN = configure \
       src/cigraph/configure \
       src/cigraph/src/config.h.in \
       src/Makevars.in \
       src/Makevars.win \
       DESCRIPTION \
       NEWS.md \
       src/cigraph/LICENSE \
       src/leidenalg/LICENSE

# GLPK
#$(info make glpk next)

GLPK := $(shell cd $(top_srcdir); git ls-files --full-name optional/glpk)
GLPK2 := $(patsubst optional/glpk/%, src/cigraph/src/glpk/%, $(GLPK))

$(GLPK2): src/cigraph/src/%: $(top_srcdir)/optional/%
	mkdir -p $(@D) && cp $< $@

# Simpleraytracer
#$(info make ray tracer next)

RAY := $(shell cd $(top_srcdir); git ls-files --full-name optional/simpleraytracer)
RAY2 := $(patsubst optional/simpleraytracer/%, \
	  src/cigraph/src/simpleraytracer/%, $(RAY))

$(RAY2): src/cigraph/src/%: $(top_srcdir)/optional/%
	mkdir -p $(@D) && cp $< $@

# configure apparently wants to find install-sh in the
# build directory when configure.ac has the macro
# AC_CONFIG_SUBDIRS(). The script has no function.
install-sh: templates/install-sh.tpl
	cp templates/install-sh.tpl install-sh

# configure files
#$(info make configure files next)

configure: configure.ac install-sh
	autoconf

src/cigraph/configure src/cigraph/src/config.h.in: src/cigraph/configure.ac
	cd src/cigraph; autoheader; autoconf

# DESCRIPTION file, we re-generate it only if the VERSION number
# changes
#$(info make description file next)

DESCRIPTION: templates/DESCRIPTION.tpl version_number
	sed 's/^Version: .*$$/Version: '$(VERSION_LEIDENBASE)'/' $< > $@

# LICENSE files for C igraph and leidenalg.
src/cigraph/LICENSE: LICENSE.GPL_2
	mkdir -p $(@D) && cp $< $@

src/leidenalg/LICENSE: LICENSE.GPL_3
	mkdir -p $(@D) && cp $< $@

# This is the list of all object files in the R package,
# we write it to a file to be able to depend on it.
# Makevars.in and Makevars.win are only regenerated if 
# the list of object files changes.
#$(info make objects list next)

OBJECTS := $(shell echo $(CSRC2) $(ARPACK) $(GLPK2) $(RAY2) $(CXXSRC) | \
                sed 's/^src\///'  |                                      \
		tr ' ' '\n' |                                            \
	        grep -E '\.(c|cpp|cc|f|l|y)$$' | 			 \
		grep -F -v '/t_cholmod' | 				 \
		grep -F -v f2c/arithchk.c | grep -F -v f2c_dummy.c |	 \
		sed 's/\.[^\.][^\.]*$$/.o/' | 			 	 \
		sed 's/^src\///' | sed 's/^tools\/arpack\///' )

object_files: force
	@echo '$(OBJECTS)' | cmp -s - $@ || echo '$(OBJECTS)' > $@

configure.ac: templates/configure.ac.leidenbase.tpl
	sed 's/@VERSION@/'$(VERSION_LEIDENBASE)'/g' $< >$@

src/cigraph/configure.ac: templates/configure.ac.igraph.tpl
	sed 's/@VERSION@/'$(VERSION_IGRAPH)'/g' $< >$@

src/Makevars.in: templates/Makevars.in.tpl object_files
	sed 's/@VERSION_IGRAPH@/'$(VERSION_IGRAPH)'/g' $< >$@
	printf "%s" "OBJECTS=" >> $@
	cat object_files >> $@

src/Makevars.win: templates/Makevars.win.tpl object_files
	sed 's/@VERSION_IGRAPH@/'$(VERSION_IGRAPH)'/g' $< >$@
	printf "%s" "OBJECTS=" >> $@
	cat object_files >> $@

# We have everything, here we go

leidenbase: leidenbase_$(VERSION_LEIDENBASE).tar.gz

leidenbase_$(VERSION_LEIDENBASE).tar.gz: $(CGEN) $(CSRC2) $(CINC2) $(PARSER3) $(RSRC) $(RGEN) \
			  $(CGEN) $(GLPK2) $(RAY2) $(ARPACK) $(CXXSRC)
	rm -f src/cigraph/src/config.h
	rm -f src/Makevars
	rm -rf leidenbase
	mkdir -p src/cigraph/src
	touch src/cigraph/src/config.h
	chmod 700 configure
	Rscript -e 'devtools::build(path = ".")'

#############

.PHONY: all leidenbase force
